In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import os

In [2]:
df = pd.read_csv("../Resources/Inspection.csv")
df.head()

,Seg_ID,UP_MH,DS_MH,"Dia., Inch","Length, Ft","MWL, %","DS, % depth",Defect Bucket
0,1,36206.0,36207.0,42,200,95,0.0,1
1,2,36206.0,36207.0,60,200,95,0.0,1
2,3,36206.0,36207.0,60,200,95,0.0,1
3,4,36204.0,838.0,102,651,80,0.0,4
4,5,8197.0,36206.0,96,950,75,0.0,1

In [3]:
# Get the target variables. 
target = df["Defect Bucket"]
target_names = [1,2,3,4,5,6]

In [4]:
df.describe()

,Seg_ID,UP_MH,DS_MH,"Dia., Inch","Length, Ft","MWL, %","DS, % depth",Defect Bucket
count,219.000000,219.000000,219.000000,219.000000,219.000000,219.000000,219.000000,219.000000
mean,110.000000,1058.079635,1045.365936,52.269406,971.493151,35.251142,0.651689,2.799087
std,63.364028,4981.960885,4971.212615,19.566765,930.617613,14.677135,2.448967,2.162185
min,1.000000,2.000000,1.600000,24.000000,11.000000,10.000000,0.000000,1.000000
25%,55.500000,54.500000,52.500000,36.000000,478.500000,25.000000,0.000000,2.000000
50%,110.000000,98.000000,95.000000,48.000000,601.000000,35.000000,0.000000,2.000000
75%,164.500000,220.500000,218.500000,69.000000,1358.500000,40.000000,0.000000,3.000000
max,219.000000,36206.000000,36207.000000,102.000000,8835.000000,95.000000,10.000000,10.000000

In [5]:
# Get the features. 
data = df.drop("Defect Bucket", axis=1)
feature_names = data.columns
data

     Seg_ID    UP_MH    DS_MH  Dia., Inch  Length, Ft  MWL, %  DS, % depth
0         1  36206.0  36207.0          42         200      95         0.00
1         2  36206.0  36207.0          60         200      95         0.00
2         3  36206.0  36207.0          60         200      95         0.00
3         4  36204.0    838.0         102         651      80         0.00
4         5   8197.0  36206.0          96         950      75         0.00
..      ...      ...      ...         ...         ...     ...          ...
214     215    401.0    400.0          39         634      40         0.00
215     216    404.0    403.0          54         897      25         0.04
216     217    400.0     31.0          54        3370      25         0.00
217     218    403.0    402.0          39         966      40         0.00
218     219    402.0    401.0          39        1010      40         0.00

[219 rows x 7 columns]

In [6]:
# Split data into training and testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=42)

In [7]:
# Support vector machine linear classifier
from sklearn.svm import SVC 
model = SVC(kernel='linear')
model.fit(X_train, y_train)

SVC(kernel='linear')

In [25]:
# Model Accuracy
print('Test Acc: %.3f' % model.score(X_test, y_test))

Test Acc: 0.673

In [ ]:
# Calculate the classification report
from sklearn.metrics import classification_report
predictions = model.predict(X_test)
print(classification_report(y_test, predictions,
                            target_names=target_names))